### ISSUE TITLE
Improve benchmark section in documentation

### ISSUE THREAD

**Issue by aguspesce** [ggciag/mandyoc#23]
It is a good idea to include in the benchmark section how to run the models that we used to create the benchmark and where they are.

So, my suggestions are: 
* Explain where the models are in the documentation. 
*  Create a README file, which explains how to run and create the models in each models  folder.

**Comment by rafaelmds** [comment]
@aguspesce , is this being covered - at least partially (README file following your second suggestion) - by #25?

**Comment by rafaelmds** [comment]
I'll take this.

@aguspesce could you please see my question above?

Will start PR now you can follow.

**Comment by aguspesce** [comment]
@rafaelmds ... I have not put any information about the examples and the benchmark in the documentation yet.  
Would you want to improve the examples  and benckmark documentation? Start a new PR with this improvement.
