### ISSUE TITLE
Setup and update docker image

### ISSUE THREAD

**Issue by rafaelmds** [ggciag/mandyoc#24]
Some time ago I tested a [docker image](https://hub.docker.com/repository/docker/rafaelmds/mandyoc/general) for mandyoc.

I will update it manually for now, but we should automate it as well.

**Comment by rafaelmds** [comment]
I did some tests on my [fork](https://github.com/rafaelmds/mandyoc).
After cache, new builds take approx 1 minute, so I think its fine to add docker image build action here.
Currently, I think its better to only build on releases.

**Comment by aguspesce** [comment]
@rafaelmds ... It is great!
Good Job!
