### ISSUE TITLE
Complite the authors file

### ISSUE THREAD

**Issue by aguspesce** [ggciag/mandyoc#4]
@victorsacek, @rafaelmds  and Jamison. 
It is necessary to complete the [AUTHORS file](https://github.com/ggciag/mandyoc/blob/main/AUTHORS.md)

**Comment by rafaelmds** [comment]
How do we proceed to that?
Should we send the info here and someone updated it?

Btw @jamisonassuncao is here

**Comment by aguspesce** [comment]
Maybe you can add a suggestion with the info

**Comment by rafaelmds** [comment]
Fixed by #28
