### ISSUE TITLE
JOSS REVIEW: Add Basic Scaling examples

### ISSUE THREAD

**Issue by rbeucher** [ggciag/mandyoc#48]
Please add some scaling tests to show how the code behaves on multiple processors.
Can be Weak and/or Strong scaling.

**Comment by rafaelmds** [comment]
We added two scaling tests for [ vanKeken1997_case1a](https://ggciag.github.io/mandyoc/files/benchmarks.html#basic-scaling) and [Crameri](https://ggciag.github.io/mandyoc/files/benchmarks.html#id25) benchmarks.

Merged in #67.
