### ISSUE TITLE
JOSS REVIEW: Model progression is hard to track

### ISSUE THREAD

**Issue by rbeucher** [ggciag/mandyoc#49]
I am running the examples. All seems to go as expected. However, I find it really hard to track progress of the model.
Can you add a step number, time evolution etc?

**Comment by rbeucher** [comment]
OK I see now:

```
step = 6, time = 5.08e+04 yr, dt = 8.46e+03 yr
Thermal (building): 0.239868 s
Thermal (solution): 0.049435 s
```

Still hard to understand what the code is doing. If it is iterating on a solve etc.

Maybe try to clarify that?

**Comment by victorsacek** [comment]
During the simulation, we added a few sentences to facilitate the reading of the model progression.
